### ISSUE TITLE
NaN Loss occurred during training

### ISSUE THREAD

**Issue by MengQiDWangChao** [intel/handwritten-chinese-ocr-samples#10]
When I was training, I made the following mistakes, 
![image](https://user-images.githubusercontent.com/32353044/156912325-2b814bd5-dbf5-4490-830d-feab91b411e9.png)

what might be the reasons?

i see such annotation:
![image](https://user-images.githubusercontent.com/32353044/156912332-482867d3-1a64-4b78-bb27-e1ef50c86b21.png)

**Comment by MengQiDWangChao** [comment]
it's because my image is short then then preds' length is shorter than labels

**Comment by shengyudingli** [comment]
> 

Hello. how do you solve this problem? Would you please share your solutions?
